name: Azure Function App Deploy using Publish Profile

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip Function App
        run: |
          zip -r functionapp.zip ./*

      - name: Deploy via curl using ZipDeploy credentials
        env:
          ZIP_DEPLOY_USER: ${{ secrets.ZIP_DEPLOY_USERNAME }}
          ZIP_DEPLOY_PASS: ${{ secrets.ZIP_DEPLOY_PASSWORD }}
        run: |
          curl -X POST -u $ZIP_DEPLOY_USER:$ZIP_DEPLOY_PASS \
            --data-binary @functionapp.zip \
            https://spd-work.scm.azurewebsites.net/api/zipdeploy
