name: Azure Function Deploy with Publish Profile

on:
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip Azure Function App
        run: |
          zip -r functionapp.zip ./*

      - name: Deploy to Azure Function App via Publish Profile
        uses: Azure/functions-action@v1
        with:
          app-name: 'spd-work'
          package: 'functionapp.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
