name: Azure Function Deploy With CICD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  # use latest v3

      - name: Set up Python
        uses: actions/setup-python@v4  # use latest v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install required Python modules
        run: |
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Zip the Azure Function Deploy folder
        run: |
          zip -r work.zip . -x "*.git*" "*.github*" "work.zip"

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Optional - Show Account Info
        run: |
          az account show
          az group list

      - name: Deploy the Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group "bhanu-test" \
            --name "spd-work" \
            --src "work.zip"
