name: Deploy Azure Function App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Zip function app files
        run: |
          zip -r functionapp.zip ./*

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'spd-work'  # Replace with your Function App name
          package: 'functionapp.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
